# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4000a9f54b63d85bfd85e3ee5d149f74f204dc6edd8d0dca92ee586753a30ce558f6ab8f8d23db38d39f1e0425053fad3d8ab750dd15658b113ab958581a3b8

test:
  secret_key_base: 3adb110f8bd81d36fec38b3c3e38b100dc3636f41f9ac5f68ff9d0424c400c446956f9d8b59892ac2d96e974943498aa0eee4cd09da14825837174957275f7e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
